# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d071246614d4a9ebf1d313980dca639bc66b8aef94f8d78653392deaa563ae1f1ecad32b35a1d2feeaa6863bf7d6b48153b7a8b09c74e3100c79abe725cd377e

test:
  secret_key_base: 77cc797d941e7903846afe9396207f9cc0519317a2ead7870e10ecd470cda2cad7d5a26121a6b22f49de4b4a69db0a3cbc3ca66332f835cba9a61a88b6f00a33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
